vim9script

plug#begin()
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'tomtom/tcomment_vim'
Plug 'jiangmiao/auto-pairs'
Plug 'girishji/vimcomplete'
Plug 'airblade/vim-rooter'
Plug 'yegappan/lsp'
# Colorscheme
Plug 'ydzhou/monocolor.vim'
Plug 'NLKNguyen/papercolor-theme'
plug#end()

set nocompatible
set mouse=a
set backspace=indent,eol,start
set autoread
set gcr=a:blinkon0
set noeb vb t_vb=
if has('autocmd')
	autocmd GUIEnter * set visualbell t_vb=
endif
set encoding=UTF-8
set wildmenu
set wildmode=longest:full,full
set nofoldenable

filetype on
filetype plugin on
filetype indent on

set wrap lbr
set display=lastline
set tabstop=4 shiftwidth=4 softtabstop=4 expandtab shiftround
set showmatch matchtime=1 matchpairs&
set cindent autoindent
set clipboard+=unnamed
set number signcolumn=number

set laststatus=2
set statusline=%03l,%03v\ %p%%\ %<%=%F%m%r%h%w

syntax on
if has("gui_running")
    if has("mac")
        set guioptions-=m
        set guioptions-=r
        set guifont=Source\ Code\ Pro:h14
    else
        set guifont=\ 12
    endif
	set guioptions-=T
	set guioptions-=e
	set guioptions-=L
	set lines=50
	set columns=150
	set linespace=2
	colorscheme PaperColor
    autocmd InsertEnter,InsertLeave * set cul!
else
    &t_SI = "\e[6 q"
    &t_EI = "\e[2 q"
    # Fix Kitty issue with vim colorscheme background
    &t_ut = ''
    set t_Co=256
endif

set incsearch ignorecase smartcase

# Backup
set noswapfile
set backupdir=~/.vim/backup

g:mapleader = ","
map ; <C-d>
map ' <C-u>
map <silent> <Leader>, <C-o>
map <silent> <Leader>. <C-i>
# Disable mouse double clicking for accidentally switching to visual mode
map <2-LeftMouse> <Nop>
# standard keys for wrapped lines
set whichwrap+=<,>,[,]
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
# easier moving of code block
vnoremap < <gv
vnoremap > >gv
# Paste from 0 register to avoid cannot paste after deletion
nnoremap d "_d
xnoremap d "_d
nnoremap x "_x
xnoremap x "_x
nnoremap s "_s
xnoremap s "_s
map <C-n> :Explore<CR>

autocmd BufNewFile,BufReadPost *.md set filetype=markdown

# Quickfix window auto close when closing a window
autocmd WinEnter * if winnr('$') == 1 && getbufvar(winbufnr(winnr()), "&buftype") == "quickfix"|q|endif

g:netrw_liststyle = 3

source ~/dotvim/vim/configs/fzf.vim
source ~/dotvim/vim/configs/lsp.vim
source ~/dotvim/vim/configs/cmp.vim

# TComment
# g:tcommentOptions = {'whitespace' : 'no'}
map <silent> <Leader>c :TComment<CR>
